### ISSUE TITLE
[Packages] Configurazione non valida

### ISSUE THREAD

**Issue by Danny89530** [marco-hacs/Consumption-control-and-appliance-management#1]
Ciao Marco!
Ho trovato il blueprint sulla community page di HA e volevo provarlo nella mia configurazione.
Ho creato lo yaml nella cartella dei packages, dopo aver abilitato questi ultimi nel file configuration.yaml

```
[...]
homeassistant:
  packages: !include_dir_merge_named packages/
[...]
```
Prima di procedere al riavvio ho verificato la configurazione tramite gli strumenti di sviluppo ma la configurazione sembra non esser valida.

![immagine](https://user-images.githubusercontent.com/3729455/211798323-38de631e-5ebd-484f-beef-4e4965d67409.png)

Cosa sbaglio?

**Comment by Danny89530** [comment]
Come non detto, avendo utilizzato la funzione `include_dir_merge_named` il file da te condiviso doveva essere modificato con il nome del package in intestazione.
Grazie comunque!

**Comment by marco-hacs** [comment]
Perfetto... ti stavo rispondendo... fammi sapere se riscontri problemi
